version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"  # Set the AWS region explicitly
    MAVEN_OPTS: "--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED"
    REPOSITORY_URI: "061051220936.dkr.ecr.us-east-1.amazonaws.com/myproject-registry"

phases:
  install:
    commands:
      - echo Installing Maven dependencies...
      - mvn clean install  # This will run your Maven build
      - aws --version  # Ensure AWS CLI version is 2 or later
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"order-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/order-service.jar
